// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByQe8BrCWvAKYow64d6FIRxh3AB7GJCVk',
    appId: '1:167478436854:web:aa8619b4a741430ece9dd7',
    messagingSenderId: '167478436854',
    projectId: 'endroid-a09b6',
    authDomain: 'endroid-a09b6.firebaseapp.com',
    storageBucket: 'endroid-a09b6.firebasestorage.app',
    measurementId: 'G-0KLHW785RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhE8OCPSLfqHTY8CSfT3OrC1A1v6BhLjg',
    appId: '1:167478436854:android:fe657615036c925ace9dd7',
    messagingSenderId: '167478436854',
    projectId: 'endroid-a09b6',
    storageBucket: 'endroid-a09b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXSrBIIR6fsfLKZ__uA3CPsA_IaoKudLg',
    appId: '1:167478436854:ios:131127249de2c292ce9dd7',
    messagingSenderId: '167478436854',
    projectId: 'endroid-a09b6',
    storageBucket: 'endroid-a09b6.firebasestorage.app',
    iosBundleId: 'com.example.endroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXSrBIIR6fsfLKZ__uA3CPsA_IaoKudLg',
    appId: '1:167478436854:ios:131127249de2c292ce9dd7',
    messagingSenderId: '167478436854',
    projectId: 'endroid-a09b6',
    storageBucket: 'endroid-a09b6.firebasestorage.app',
    iosBundleId: 'com.example.endroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByQe8BrCWvAKYow64d6FIRxh3AB7GJCVk',
    appId: '1:167478436854:web:558c0be4f3ae394cce9dd7',
    messagingSenderId: '167478436854',
    projectId: 'endroid-a09b6',
    authDomain: 'endroid-a09b6.firebaseapp.com',
    storageBucket: 'endroid-a09b6.firebasestorage.app',
    measurementId: 'G-SP6103KM5L',
  );

}